# serverless.yml

service: scion-gpl
plugins:
    - serverless-offline
    - serverless-webpack
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules:
            forceInclude:
                - pg
environment:
    DB_HOST: ${param:DB_HOST}
    DB_NAME: ${param:DB_NAME}
    DB_PASSWORD: ${param:DB_PASSWORD}
    DB_USERNAME: ${param:DB_USERNAME}
    DB_SCHEMA: ${param:DB_SCHEMA}
    DB_SEARCH_PATH: ${param:DB_SEARCH_PATH}
    DB_LOGGING: ${param:DB_LOGGING}
    PORT: ${param:DB_USERNAME}
    API_BASE_URL: ${param:API_BASE_URL}
    CRYPT_SALT: ${param:API_BASE_URL}
    JWT_SECRET: ${param:JWT_SECRET}
    ORIGIN_WHITELIST: ${param:JWT_SECRET}
provider:
    name: aws
    runtime: nodejs12.x
    stage: "dev"
    region: us-west-2
    apiGateway:
        shouldStartNameWithService: true
    vpc:
        securityGroupIds:
            - sg-7fda085d
        subnetIds:
            - subnet-2147700a
            - subnet-2eb87664
            - subnet-8a61ccf2
            - subnet-872599da
functions:
    graphql:
        handler: src/index.handler
        events:
            - http:
                  path: gql/v1/
                  method: POST
        role: arn:aws:iam::956828706551:role/lamda-vpc-role
