# serverless.yml

service: scion-gpl
plugins:
    - serverless-offline
    - serverless-webpack
    - serverless-dotenv-plugin
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules:
            forceInclude:
                - pg
    keys: $(file(./env.config.js))
provider:
    name: aws
    runtime: nodejs12.x
    stage: "dev"
    region: us-west-2
    apiGateway:
        shouldStartNameWithService: true
    vpc:
        securityGroupIds:
            - sg-7fda085d
        subnetIds:
            - subnet-2147700a
            - subnet-2eb87664
            - subnet-8a61ccf2
            - subnet-872599da
functions:
    graphql:
        environment:
            DB_HOST: $(self:custom.keys.dbHost)
            DB_NAME: $(self:custom.keys.dbName)
            DB_PASSWORD: $(self:custom.keys.dbPassword)
            DB_USERNAME: $(self:custom.keys.dbUsername)
            DB_SCHEMA: $(self:custom.keys.dbSchema)
            DB_SEARCH_PATH: $(self:custom.keys.dbSearchPath)
            DB_LOGGING: $(self:custom.keys.dbLogging)
            PORT: $(self:custom.keys).port
            API_BASE_URL: $(self:custom.keys).apiBase
            CRYPT_SALT: $(self:custom.keys.cryptSalt)
            JWT_SECRET: $(self:custom.keys.jwtSecret)
            ORIGIN_WHITELIST: $(self:custom.keys.originWhitelist)
        handler: src/index.handler
        events:
            - http:
                  path: gql/v1/
                  method: POST
        role: arn:aws:iam::956828706551:role/lamda-vpc-role
