# serverless.yml

service: scion-gpl
plugins:
    - serverless-offline
    - serverless-webpack
    - serverless-dotenv-plugin
custom:
    webpack:
        webpackConfig: ./webpack.config.js
        includeModules:
            forceInclude:
                - pg
provider:
    name: aws
    runtime: nodejs12.x
    stage: "dev"
    region: us-west-2
    apiGateway:
        shouldStartNameWithService: true
    vpc:
        securityGroupIds:
            - sg-7fda085d
        subnetIds:
            - subnet-2147700a
            - subnet-2eb87664
            - subnet-8a61ccf2
            - subnet-872599da
functions:
    graphql:
        environment:
            - DB_HOST = DB_HOST
            - DB_NAME = DB_NAME
            - DB_PASSWORD = DB_PASSWORD
            - DB_USERNAME = DB_USERNAME
            - DB_SCHEMA = DB_SCHEMA
            - DB_SEARCH_PATH = DB_SEARCH_PATH
            - DB_LOGGING = DB_LOGGING
            - PORT = PORT
            - API_BASE_URL = API_BASE_URL
            - CRYPT_SALT = CRYPT_SALT
            - JWT_SECRET = JWT_SECRET
            - ORIGIN_WHITELIST = ORIGIN_WHITELIST
        handler: src/index.handler
        events:
            - http:
                  path: gql/v1/
                  method: POST
        role: arn:aws:iam::956828706551:role/lamda-vpc-role
